Repository Soldann/MORB_SLAM, pull requests merged in 2022-07, with the labels that each got.

#41 removed duplicate matlambda(0,0) from being set twice to 1e3
  src/Optimizer.cc
Labels: needs validation

#67 Enable emitter for additional depth info
  Examples/Stereo-Inertial/stereo_inertial_realsense_D435i.cc
Labels: enhancement

#75 fix active map reset and imu pose segmentation faults
  src/KeyFrameDatabase.cc
  src/Optimizer.cc
Labels: bug

#78 Changed viewer default to follow camera, start at camera view, and sh…
  src/Viewer.cc
Labels: enhancement

#82 Update the build.sh to properly handle -j flag
  build.sh
Labels: bug
